name: Docker CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set short SHA and timestamp
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TIMESTAMP=$(date -u +"%Y%m%d-%H%M")
          IMAGE_TAG="$SHORT_SHA-$TIMESTAMP"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image (no push)
        run: docker build -t dummy/2025cloud:$IMAGE_TAG .
